repos:

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-docstring-first
      -   id: check-added-large-files
          args: ['--maxkb=5000']
      -   id: check-yaml

  -   repo: https://github.com/ambv/black
      rev: 19.3b0
      hooks:
      - id: black
